### ISSUE TITLE
search does not work

### ISSUE THREAD

**Issue by javamonkey79** [radek-novak/json-commander#2]
The default browser search behavior does not work when the output json section (query result) is emitted. To search, you have to then go to the original (non query) response section.

**Comment by radek-novak** [comment]
![jspath-search](https://cloud.githubusercontent.com/assets/6372548/22176654/ac0b5ade-e00f-11e6-918e-c599a5e2f843.png)
it seems to work for me if you mean this

**Comment by javamonkey79** [comment]
Yes, you're right. I just checked it, and the problem was actually that I still had json viewer plugin installed as well. Thanks for checking it out!
